language : python
python :
  - "3.6"

services :
  -vagrant

install:
  - sudo apt-get update -q
  - sudo apt-get install -q virtualbox --fix-missing
  - sudo wget -nv https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i vagrant_1.7.2_x86_64.deb
  - bundle instal
sript:
  -vagrant-compose run  recipe_app sh -c "python manage.py test && flake8"
